### PR TITLE
Modified legends and description based on inputs from implementation call

### PR DESCRIPTION
**Pull request by Pardhu448**
Added better description of the graphs, documentation and data source are added.

### CODE REVIEW

**Comment by SadaqatMulla** [comment]
What is time period of latest Tools log level data that has been added?

**Comment by Pardhu448** [comment]
It has all the syncthing data till Jan, 2019.  But we took only data corresponding to July 2018 to Jan, 2019 for graphs. I kept it for the sake of completeness.

**Comment by SadaqatMulla** [comment]
Then I hope the observation period in the graphs names have been changed accordingly. I think we should try to have a graphs that can change dynamically based on  available timeline. Shall I go ahead and merge?

**Comment by Pardhu448** [comment]
Yeah. Observation period in the graphs are appropriate. Yes, that would be
best thing to do. Will note this down among the improvements.

**Pull request merged**
